name: t_store
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

# ---------------- PACKAGES ---------------- #
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.20.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  connectivity_plus: ^6.1.2
  flutter_native_splash: ^2.4.3
  smooth_page_indicator: ^1.1.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2

  # Firebase
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2

  # ----------------- ./ PACKAGES END ----------------- #

  # ---------------- DEV DEPENDENCIES ---------------- #

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # ------------------ LoCAL ASSETS ------------------ #
  assets:
    - assets/images/on_boarding_images/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/icons/payment_method/
    - assets/logos/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/content/
    - assets/images/products/
    - assets/images/reviews/

  # ------------------ FONTS ------------------ #
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
